### PR TITLE
Update for Py3/Quippy support

### PR DESCRIPTION
**Pull request by Andrew-S-Rosen**
I have updated glosim2 to make it compatible with Python 3 and commit 10,060 of Quippy (https://github.com/libAtoms/QUIP/commit/6b344d45f19b5d12fb5e63f34a0aef09a922b3dd). This addresses https://github.com/cosmo-epfl/glosim2/issues/5

### CODE REVIEW

**Comment by ceriottm** [comment]
@sandipde any chance you can have a look? It'd be good to make this compatible w/ latest quippy, even though we're moving to deprecating it.

**Comment by Andrew-S-Rosen** [comment]
@ceriottm: does glosim2 end up doing the same thing as the SOAP function in quippy with average=True? What is the difference here?

**Comment by ceriottm** [comment]
well, if you use the average SOAP yes, if you use rematch no. there are a few other subtleties, such as the possibility of defining "atom kits"

**Comment by Andrew-S-Rosen** [comment]
Of course. Makes sense.

FYI: I only debugged the code such that the example Jupyter notebook ran without error. I didn't have any other examples to go by.

**Comment by sandipde** [comment]
Thanks for this. I will check too and report if any things goes wrong.

**Comment by Andrew-S-Rosen** [comment]
I just found a few areas not covered by the example where qp.Atoms was
called. That will have to be fixed. Otherwise, I think the other issues of
print statements and iteritems - - > items should be fixed.

**Pull request merged**
